server {
    listen 8080;
    add_header Content-Security-Policy "default-src 'self'; style-src 'self'; script-src 'self'; object-src 'none';" always;
    add_header X-Robots-Tag "noindex, nofollow" always;
    location / { 
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html; 
    }
}